//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [NonPersistent]
    public partial class Employee : XPLiteObject
    {
        string fEmployeeAccountID;
        [Key]
        [Size(7)]
        public string EmployeeAccountID
        {
            get { return fEmployeeAccountID; }
            set { SetPropertyValue<string>("EmployeeAccountID", ref fEmployeeAccountID, value); }
        }
        int fEmployeeNumber;
        public int EmployeeNumber
        {
            get { return fEmployeeNumber; }
            set { SetPropertyValue<int>("EmployeeNumber", ref fEmployeeNumber, value); }
        }
        string fName;
        [Size(250)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fDeptName;
        [Size(250)]
        public string DeptName
        {
            get { return fDeptName; }
            set { SetPropertyValue<string>("DeptName", ref fDeptName, value); }
        }
        string fDegreeName;
        [Size(178)]
        public string DegreeName
        {
            get { return fDegreeName; }
            set { SetPropertyValue<string>("DegreeName", ref fDegreeName, value); }
        }
        string fCostName;
        [Size(250)]
        public string CostName
        {
            get { return fCostName; }
            set { SetPropertyValue<string>("CostName", ref fCostName, value); }
        }
        string fJobName;
        [Size(128)]
        public string JobName
        {
            get { return fJobName; }
            set { SetPropertyValue<string>("JobName", ref fJobName, value); }
        }
    }

}
