//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"EmployeeFullDataView")]
    public partial class Employee : XPLiteObject
    {
        string fAccountID;
        [Key]
        [Size(7)]
        [Persistent(@"EmployeeAccountID")]
        public string AccountID
        {
            get { return fAccountID; }
            set { SetPropertyValue<string>("AccountID", ref fAccountID, value); }
        }
        int fEmployeeNumber;
        public int EmployeeNumber
        {
            get { return fEmployeeNumber; }
            set { SetPropertyValue<int>("EmployeeNumber", ref fEmployeeNumber, value); }
        }
        string fName;
        [Size(250)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fDegreeName;
        public string DegreeName
        {
            get { return fDegreeName; }
            set { SetPropertyValue<string>("DegreeName", ref fDegreeName, value); }
        }
        string fJobName;
        [Size(150)]
        public string JobName
        {
            get { return fJobName; }
            set { SetPropertyValue<string>("JobName", ref fJobName, value); }
        }
        short fIsRetired;
        public short IsRetired
        {
            get { return fIsRetired; }
            set { SetPropertyValue<short>("IsRetired", ref fIsRetired, value); }
        }
    }

}
