//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_EquipmentProductsTable")]
    public partial class EquipmentProducts : XPLiteObject
    {
        int fProductId;
        [Key]
        public int ProductId
        {
            get { return fProductId; }
            set { SetPropertyValue<int>("ProductId", ref fProductId, value); }
        }
        int fEquipmentId;
        [Indexed(@"SalesAccountID", Name = @"IX_PRD_EquipmentProductsTable", Unique = true)]
        public int EquipmentId
        {
            get { return fEquipmentId; }
            set { SetPropertyValue<int>("EquipmentId", ref fEquipmentId, value); }
        }
        string fSalesAccountID;
        [Size(7)]
        public string SalesAccountID
        {
            get { return fSalesAccountID; }
            set { SetPropertyValue<string>("SalesAccountID", ref fSalesAccountID, value); }
        }
    }

}
