//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_EquipmentTable")]
    public partial class Equipment : XPLiteObject
    {
        int fEquipmentId;
        [Key]
        public int EquipmentId
        {
            get { return fEquipmentId; }
            set { SetPropertyValue<int>("EquipmentId", ref fEquipmentId, value); }
        }
        string fEquipmentName;
        [Size(250)]
        public string EquipmentName
        {
            get { return fEquipmentName; }
            set { SetPropertyValue<string>("EquipmentName", ref fEquipmentName, value); }
        }
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>("StartDate", ref fStartDate, value); }
        }
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>("EndDate", ref fEndDate, value); }
        }
        Location fLocationId;
        [Association(@"EquipmentReferencesLocation")]
        public Location LocationId
        {
            get { return fLocationId; }
            set { SetPropertyValue<Location>("LocationId", ref fLocationId, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>("Active", ref fActive, value); }
        }
        string fFixedAccountId;
        [Size(7)]
        public string FixedAccountId
        {
            get { return fFixedAccountId; }
            set { SetPropertyValue<string>("FixedAccountId", ref fFixedAccountId, value); }
        }
        [Association(@"TransJournalLineReferencesEquipment")]
        public XPCollection<TransJournalLine> TransJournalLines { get { return GetCollection<TransJournalLine>("TransJournalLines"); } }
    }

}
