//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_LocationTable")]
    public partial class Location : XPLiteObject
    {
        int fLocationId;
        [Key]
        public int LocationId
        {
            get { return fLocationId; }
            set { SetPropertyValue<int>("LocationId", ref fLocationId, value); }
        }
        string fLocationName;
        [Size(150)]
        public string LocationName
        {
            get { return fLocationName; }
            set { SetPropertyValue<string>("LocationName", ref fLocationName, value); }
        }
        [Association(@"EquipmentReferencesLocation")]
        public XPCollection<Equipment> Equipments { get { return GetCollection<Equipment>("Equipments"); } }
    }

}
