//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_ProductListView")]
    public partial class ProductList : XPLiteObject
    {
        int fProductId;
        [Key]
        public int ProductId
        {
            get { return fProductId; }
            set { SetPropertyValue<int>("ProductId", ref fProductId, value); }
        }
        string fItemName;
        [Size(451)]
        public string ItemName
        {
            get { return fItemName; }
            set { SetPropertyValue<string>("ItemName", ref fItemName, value); }
        }
    }

}
