//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_ShiftTable")]
    public partial class Shift : XPLiteObject
    {
        int fShiftId;
        [Key]
        public int ShiftId
        {
            get { return fShiftId; }
            set { SetPropertyValue<int>("ShiftId", ref fShiftId, value); }
        }
        string fShiftName;
        [Size(50)]
        public string ShiftName
        {
            get { return fShiftName; }
            set { SetPropertyValue<string>("ShiftName", ref fShiftName, value); }
        }
    }

}
