//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_TransJournalLineTable")]
    public partial class TransJournalLine : XPLiteObject
    {
        int fRecId;
        [Key(true)]
        public int RecId
        {
            get { return fRecId; }
            set { SetPropertyValue<int>("RecId", ref fRecId, value); }
        }
        TransJournal fJournalId;
        [Indexed(@"ProductId", Name = @"IX_PRD_TransJournalLineTable")]
        [Association(@"TransJournalLineReferencesTransJournal")]
        public TransJournal JournalId
        {
            get { return fJournalId; }
            set { SetPropertyValue<TransJournal>("JournalId", ref fJournalId, value); }
        }
        EquipmentProducts fProductId;
        [ExplicitLoading(1)]
        public EquipmentProducts ProductId
        {
            get { return fProductId; }
            set { SetPropertyValue<EquipmentProducts>("ProductId", ref fProductId, value); }
        }
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>("Quantity", ref fQuantity, value); }
        }
        string fLineDescription;
        [Size(500)]
        public string LineDescription
        {
            get { return fLineDescription; }
            set { SetPropertyValue<string>("LineDescription", ref fLineDescription, value); }
        }
        Equipment fEquipmentId;
        [Association(@"TransJournalLineReferencesEquipment")]
        public Equipment EquipmentId
        {
            get { return fEquipmentId; }
            set { SetPropertyValue<Equipment>("EquipmentId", ref fEquipmentId, value); }
        }
    }

}
