//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_TransJournalTable")]
    public partial class TransJournal : XPLiteObject
    {
        int fJournalId;
        [Key(true)]
        public int JournalId
        {
            get { return fJournalId; }
            set { SetPropertyValue<int>("JournalId", ref fJournalId, value); }
        }
        Shift fShiftId;
        [Association(@"TransJournalReferencesShift")]
        public Shift ShiftId
        {
            get { return fShiftId; }
            set { SetPropertyValue<Shift>("ShiftId", ref fShiftId, value); }
        }
        DateTime fTransDate;
        public DateTime TransDate
        {
            get { return fTransDate; }
            set { SetPropertyValue<DateTime>("TransDate", ref fTransDate, value); }
        }
        decimal fWorkingHours;
        public decimal WorkingHours
        {
            get { return fWorkingHours; }
            set { SetPropertyValue<decimal>("WorkingHours", ref fWorkingHours, value); }
        }
        decimal fFaultsHours;
        public decimal FaultsHours
        {
            get { return fFaultsHours; }
            set { SetPropertyValue<decimal>("FaultsHours", ref fFaultsHours, value); }
        }
        string fDecription;
        [Size(500)]
        public string Decription
        {
            get { return fDecription; }
            set { SetPropertyValue<string>("Decription", ref fDecription, value); }
        }
        LocationsTable fLocationId;
        public LocationsTable LocationId
        {
            get { return fLocationId; }
            set { SetPropertyValue<LocationsTable>("LocationId", ref fLocationId, value); }
        }
        string fCreatedBy;
        [Size(30)]
        public string CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<string>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedAt;
        public DateTime CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<DateTime>("CreatedAt", ref fCreatedAt, value); }
        }
        string fModifiedBy;
        [Size(30)]
        public string ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<string>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedAt;
        public DateTime ModifiedAt
        {
            get { return fModifiedAt; }
            set { SetPropertyValue<DateTime>("ModifiedAt", ref fModifiedAt, value); }
        }
        int fIsApproved;
        public int IsApproved
        {
            get { return fIsApproved; }
            set { SetPropertyValue<int>("IsApproved", ref fIsApproved, value); }
        }
        Employee fShiftSupervisor;
        [Size(7)]
        public Employee ShiftSupervisor
        {
            get { return fShiftSupervisor; }
            set { SetPropertyValue<Employee>("ShiftSupervisor", ref fShiftSupervisor, value); }
        }
        [Association(@"TransJournalLineReferencesTransJournal")]
        public XPCollection<TransJournalLine> TransJournalLines { get { return GetCollection<TransJournalLine>("TransJournalLines"); } }
    }

}
