//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_TransJournalEmployeesTable")]
    public partial class TransJournalEmployees : XPLiteObject
    {
        int fRecId;
        [Key(true)]
        public int RecId
        {
            get { return fRecId; }
            set { SetPropertyValue<int>("RecId", ref fRecId, value); }
        }
        TransJournal fJournalId;
        [Association(@"TransJournalEmployeesReferencesTransJournal")]
        public TransJournal JournalId
        {
            get { return fJournalId; }
            set { SetPropertyValue<TransJournal>("JournalId", ref fJournalId, value); }
        }
        string fEmployeeAccountId;
        [Size(7)]
        public string EmployeeAccountId
        {
            get { return fEmployeeAccountId; }
            set { SetPropertyValue<string>("EmployeeAccountId", ref fEmployeeAccountId, value); }
        }
    }

}
