//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"PRD_VendorTransTypeTable")]
    public partial class VendorTransType : XPLiteObject
    {
        int fTransType;
        [Key]
        public int TransType
        {
            get { return fTransType; }
            set { SetPropertyValue<int>("TransType", ref fTransType, value); }
        }
        string fTransTypeName;
        [Size(90)]
        public string TransTypeName
        {
            get { return fTransTypeName; }
            set { SetPropertyValue<string>("TransTypeName", ref fTransTypeName, value); }
        }
    }

}
