//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [NonPersistent]
    public partial class VendorList : XPLiteObject
    {
        string fAccountID;
        [Key]
        [Size(7)]
        public string AccountID
        {
            get { return fAccountID; }
            set { SetPropertyValue<string>("AccountID", ref fAccountID, value); }
        }
        string fDisplayNumber;
        [Size(30)]
        public string DisplayNumber
        {
            get { return fDisplayNumber; }
            set { SetPropertyValue<string>("DisplayNumber", ref fDisplayNumber, value); }
        }
        string fName;
        [Size(250)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fReportHints;
        [Size(99)]
        public string ReportHints
        {
            get { return fReportHints; }
            set { SetPropertyValue<string>("ReportHints", ref fReportHints, value); }
        }
        int fActive;
        public int Active
        {
            get { return fActive; }
            set { SetPropertyValue<int>("Active", ref fActive, value); }
        }
    }

}
