//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"TSK_ArticalCategoryTable")]
    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class ArticalCategory : Line
    {
        string fCategoryName;
        [Size(500)]
        public string CategoryName
        {
            get { return fCategoryName; }
            set { SetPropertyValue<string>("CategoryName", ref fCategoryName, value); }
        }
        [Association(@"P_ProjectReferencesArticalCategory")]
        public XPCollection<Project> P_Projects { get { return GetCollection<Project>("P_Projects"); } }
    }

}
