//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"TSK_ProjectTable")]
    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class Project : Line
    {
        ArticalCategory fCategoryID;
        [Association(@"P_ProjectReferencesArticalCategory")]
        public ArticalCategory CategoryID
        {
            get { return fCategoryID; }
            set { SetPropertyValue<ArticalCategory>("CategoryID", ref fCategoryID, value); }
        }
        string fProjectDescription;
        [Size(1000)]
        public string ProjectDescription
        {
            get { return fProjectDescription; }
            set { SetPropertyValue<string>("ProjectDescription", ref fProjectDescription, value); }
        }
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>("StartDate", ref fStartDate, value); }
        }
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>("EndDate", ref fEndDate, value); }
        }
        [Association(@"P_TaskReferencesP_Project")]
        public XPCollection<Task> P_Tasks { get { return GetCollection<Task>("P_Tasks"); } }
    }

}
