//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"TSK_TaskTable")]
    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class Task : Line
    {
        string fTaskName;
        [Size(1000)]
        public string TaskName
        {
            get { return fTaskName; }
            set { SetPropertyValue<string>("TaskName", ref fTaskName, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>("Status", ref fStatus, value); }
        }
        int fAuthor;
        public int Author
        {
            get { return fAuthor; }
            set { SetPropertyValue<int>("Author", ref fAuthor, value); }
        }
        int fAssignee;
        public int Assignee
        {
            get { return fAssignee; }
            set { SetPropertyValue<int>("Assignee", ref fAssignee, value); }
        }
        Project fProjectID;
        [Association(@"P_TaskReferencesP_Project")]
        public Project ProjectID
        {
            get { return fProjectID; }
            set { SetPropertyValue<Project>("ProjectID", ref fProjectID, value); }
        }
        int fTaskTracker;
        public int TaskTracker
        {
            get { return fTaskTracker; }
            set { SetPropertyValue<int>("TaskTracker", ref fTaskTracker, value); }
        }
        int fPriority;
        public int Priority
        {
            get { return fPriority; }
            set { SetPropertyValue<int>("Priority", ref fPriority, value); }
        }
        DateTime fDueDate;
        public DateTime DueDate
        {
            get { return fDueDate; }
            set { SetPropertyValue<DateTime>("DueDate", ref fDueDate, value); }
        }
    }

}
