//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"TSK_TaskLogTable")]
    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class TaskLog : Line
    {
        int fTaskID;
        public int TaskID
        {
            get { return fTaskID; }
            set { SetPropertyValue<int>("TaskID", ref fTaskID, value); }
        }
        string fComments;
        [Size(1000)]
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>("Comments", ref fComments, value); }
        }
        decimal fSpentTimeInHours;
        public decimal SpentTimeInHours
        {
            get { return fSpentTimeInHours; }
            set { SetPropertyValue<decimal>("SpentTimeInHours", ref fSpentTimeInHours, value); }
        }
        int fActivity;
        public int Activity
        {
            get { return fActivity; }
            set { SetPropertyValue<int>("Activity", ref fActivity, value); }
        }
        string fFileName;
        [Size(50)]
        public string FileName
        {
            get { return fFileName; }
            set { SetPropertyValue<string>("FileName", ref fFileName, value); }
        }
        string fFileType;
        [Size(15)]
        public string FileType
        {
            get { return fFileType; }
            set { SetPropertyValue<string>("FileType", ref fFileType, value); }
        }
    }

}
