//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ProductionReports.ModelXpo.OmarERP
{

    [Persistent(@"TSK_TrackerTable")]
    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class Tracker : Line
    {
        string fTrackerName;
        public string TrackerName
        {
            get { return fTrackerName; }
            set { SetPropertyValue<string>("TrackerName", ref fTrackerName, value); }
        }
        string fFilterValue;
        [Size(30)]
        public string FilterValue
        {
            get { return fFilterValue; }
            set { SetPropertyValue<string>("FilterValue", ref fFilterValue, value); }
        }
        string fRemark;
        [Size(250)]
        public string Remark
        {
            get { return fRemark; }
            set { SetPropertyValue<string>("Remark", ref fRemark, value); }
        }
    }

}
