using DevExpress.Xpo;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace CoreModelWin
{
    public partial class TestFrm : CoreLib.MyForm
    {
        public TestFrm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            InitObj();
           
        }

        private void InitObj()
        {
            countryGV.ClassInfo     = typeof(CoreModel.Country);
            provinceGV.ClassInfo    = typeof(CoreModel.Province);
            cityGV.ClassInfo        = typeof(CoreModel.City);

            AppLists.AppListInfo l = new AppLists.AppListInfo(unitOfWork1);
            l.LinkLookupsToGrid(countryGV, xpCollection1);
            
            
        }
    }
}
