using DevExpress.Xpo;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace CoreModelWin
{
    public partial class TestFrm : CoreLib.MyForm
    {
        public TestFrm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
           
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            AppLists.AppListInfo list = new AppLists.AppListInfo(XpoDefault.Session);

            //list.LinkListToColumn(mySearchLookUpEdit1,typeof(CoreModel.Sequence));
            list.LinkListToColumn(colSequenceWorkflowStatus, typeof(CoreModel.Sequence));
        }

        private void myGridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
